spring:
  security:
    oauth2:
      client:
        provider:
          api-gateway:
            issuer-uri: http://localhost:8080/realms/feign-realm
        registration:
          api-gateway:
            provider: api-gateway
            scope: openid
            client-id: feign-gateway-client
            client-secret: 5c8mes0yfiw0zJEN9KCYl2xeOgXX1taZ
            authorization-grant-type: authorization_code
            redirect-uri: http://localhost:9090/login/oauth2/code/keycloak
  cloud:
    gateway:
      default-filters:
        - TokenRelay
      routes:
        - id: users-service
          uri: http://localhost:8082
          predicates:
            - Path=/users/**
server:
  port: 9090


logging:
    level:
        org:
            springframework:
                security: DEBUG